### ISSUE TITLE
Agent doesn't work after the latest client update

### ISSUE THREAD

**Issue by darshadev2011** [koxx12-dev/LunarAntiAntiAgent#4]
When I logged in today, the client updated and since then I was unable to launch the game. At first, when I clicked on the Launch button,  it would show Updating, then Launching and then get stuck at Building Cache. After a few tries I atleast got an error message saying "Illegal modifications detected". I don't know if this is fixable, but if it is, then please fix it immediately.

**Comment by ThisIsEXE01** [comment]
> ,

Same

**Comment by ThisIsEXE01** [comment]
> When I logged in today, the client updated and since then I was unable to launch the game. At first, when I clicked on the Launch button, it would show Updating, then Launching and then get stuck at Building Cache. After a few tries I atleast got an error message saying "Illegal modifications detected". I don't know if this is fixable, but if it is, then please fix it immediately.

Same

**Comment by AchuPoli** [comment]
> When I logged in today, the client updated and since then I was unable to launch the game. At first, when I clicked on the Launch button, it would show Updating, then Launching and then get stuck at Building Cache. After a few tries I atleast got an error message saying "Illegal modifications detected". I don't know if this is fixable, but if it is, then please fix it immediately.

yea me too

**Comment by IceColt** [comment]
me too

**Comment by ErzenXz** [comment]
Yes, please fix it!

**Comment by SagMestKing** [comment]
Same issue here, hope it's fixed soon

**Comment by koxx12-dev** [comment]
hello, i did some testing and i cannot reproduce this issue on lastest lunar version i have access to (v2.13..9-2407), if it would be possible what other agents are you guys using

**Comment by ThisIsEXE01** [comment]
Can someone give working agent?

**Comment by ErzenXz** [comment]
I'm only using your Anti Agent, how can that be lol, everytime i try to open Version 1.20.4 i get illegal client modification.
Is there any newer Lunar Client QT? Because if there is then that would justify it, im usint LC QT 2.5 i think.

**Comment by darshadev2011** [comment]
> hello, i did some testing and i cannot reproduce this issue on lastest lunar version i have access to (v2.13..9-2407), if it would be possible what other agents are you guys using

Uh well I dunno, my lcqt client updated to i guess obv the latest version and Im still having the problem. Im checking every single day to see if there are any changes but so far no good :( People in yt vid comments goin wild saying the agent doesn't work. Btw Im not using any other agent, just the latest Lunarantiantiagent, I tried some weaveloader agent and then disabled it coz that doesn't work either. My version is 3.2.3 btw. Would it work if I somehow find an old version of lunar client on the web and install that version?

**Comment by ErzenXz** [comment]
The latest lunar version is 3.2.3-master.2883.

**Comment by darshadev2011** [comment]
@koxx12-dev Yo can you do something about it please? Im dying to play

**Comment by AchuPoli** [comment]
> @koxx12-dev Yo can you do something about it please? Im dying to play

yea pls do something about it... in case u need it heres the log:

[2024-02-13 19:07:31.006] [info]  Patching Lunar Client Agent check...
[2024-02-13 19:07:31.127] [info]  RUNNING LCQT WITH PATCHES: ClassloaderPatch, FreelookPatch, CrackedAccountPatch, RawInputPatch, PackFixPatch
[2024-02-13 19:07:31.523] [info]  [19:07:31] [Genesis/main
[2024-02-13 19:07:31.524] [info]  /INFO] Found external file: Fabric-API-v1_20_1-0.90.7.jar
[2024-02-13 19:07:31.531] [info]  [19:07:31] [Genesis/main/INFO] 
[2024-02-13 19:07:31.531] [info]  Found external file: ReplayMod-v1_20_1-2.6.14.jar
[2024-02-13 19:07:31.532] [info]  [19:07:31] [Genesis/main/INFO] Found external file: FerriteCore-v1_20_1-6.0.0.jar
[2024-02-13 19:07:31.532] [info]  [
[2024-02-13 19:07:31.532] [info]  19:07:31] [Genesis/main/INFO] Found external file: Lithium-v1_20_1-0.11.2.jar
[2024-02-13 19:07:31.533] [info]  [19:07:31] [Genesis/main/INFO] Found external file: Noxesium-v1_20_1-1.0.3.jar
[2024-02-13 19:07:31.533] [info]  [19:07:31] [Genesis/main/INFO] Found external file: Noxesium_API-v1_20_1-1.0.3.jar
[2024-02-13 19:07:31.533] [info]  [19:07:31] [Genesis/main/INFO] Found external file: Sodium-v1_20_1-0.5.3.jar
[2024-02-13 19:07:31.533] [info]  [19:07:31] [Genesis/main/INFO] Found external file: Indium-v1_20_1-1.0.27.jar
[2024-02-13 19:07:31.534] [info]  [19:07:31] [Genesis/main/INFO] Found external file: Iris-v1_20_1-1.6.10.jar
[2024-02-13 19:07:31.598] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: common-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 3d1ce015144d9e8c67afb6c7bea44d465088760f
[2024-02-13 19:07:31.600] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: lunar-fabric-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 94164c1704be54f96056099ac3fd3ed60293393e
[2024-02-13 19:07:31.623] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: genesis-0.1.0-SNAPSHOT-all.jar with SHA-1 hash f4fe0763ee5612babf600ff896c2fcb2817bb441
[2024-02-13 19:07:31.626] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: lunar-lang.jar with SHA-1 hash 8ac3190e3564dd237aa2e33e9da303b906319101
[2024-02-13 19:07:31.626] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: lunar-emote.jar with SHA-1 hash b04f3ee8f5e43fa3b162981b50bb72fe1acabb33
[2024-02-13 19:07:31.627] [info]  
[2024-02-13 19:07:31.694] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: lunar.jar with SHA-1 hash c4bf1454c42c8bb098a3d81ccd4c98f7f137c6f8
[2024-02-13 19:07:31.706] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: modern-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 31afdbd14da884a90c94f2f456c116e4ec7bc576
[2024-02-13 19:07:31.708] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: lunar-replaymod-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash e035258e9e3d271ea3fbfddc86f0b103c768f1c3
[2024-02-13 19:07:31.709] [info]  [19:07:31] [Genesis/main/INFO] 
[2024-02-13 19:07:31.709] [info]  Found classpath URL: lunar-ferrite-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 998decd37be5a34c24637a51e9ddd3774d39c8c6
[2024-02-13 19:07:31.709] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: lunar-lithium-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash d5c0474ebbe63e0e9c9068f40c3e547f6bd4f20f
[2024-02-13 19:07:31.710] [info]  [19:07:31] [
[2024-02-13 19:07:31.710] [info]  Genesis/main/INFO] Found classpath URL: lunar-noxesium-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash e32e06dcb0e1bf78cd31be5c372352cfc9f11665
[2024-02-13 19:07:31.714] [info]  [19:07:31] [Genesis/main/INFO] Found classpath URL: lunar-sodium-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 9c427deb82d9d88df3ef97715ae534daca1ebbfb
[2024-02-13 19:07:32.509] [info]  [19:07:32] [Genesis/main/INFO] Adding pre-launch library to game classpath: .\.ichor\ichormodule-libs\net_fabricmc_fabric_loader_0_15_6-lunar-0.1.0.jar
[2024-02-13 19:07:32.620] [info]  [19:07:32] [Genesis/GameBootstrap/main/INFO] Launching Minecraft 1.20.1 v1_20_1 (parsed from 1.20.1)
[2024-02-13 19:07:35.235] [info]  LUNARCLIENT_STATUS_PREINIT
[2024-02-13 19:07:35.235] [info]  [19:07:35
[2024-02-13 19:07:35.236] [error] An error occurred while launching Lunar Client.
[2024-02-13 19:07:35.236] [error] java.lang.IllegalStateException: Failed to boot Minecraft
[2024-02-13 19:07:35.237] [error] 	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
[2024-02-13 19:07:35.237] [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-02-13 19:07:35.237] [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2024-02-13 19:07:35.237] [error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2024-02-13 19:07:35.237] [error] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2024-02-13 19:07:35.238] [error] 	at com.moonsworth.lunar.genesis.IOHHIIRCOCOHOHRIRHCORIOCI.RCICCIHHORIHRRIOICRCOIHRR(Unknown Source)
[2024-02-13 19:07:35.238] [error] 	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
[2024-02-13 19:07:35.238] [error] 	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
[2024-02-13 19:07:35.238] [error] Caused by: java.lang.NoClassDefFoundError: io/github/nilsen84/lcqt/patches/ClassloaderPatch
[2024-02-13 19:07:35.239] [error] 	at com.moonsworth.lunar.genesis.RCROHRIHRCRRRCHCOCCCCIHOR.loadClass(Unknown Source)
[2024-02-13 19:07:35.239] [error] 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[2024-02-13 19:07:35.239] [error] 	at java.base/java.lang.Class.forName0(Native Method)
[2024-02-13 19:07:35.239] [error] 	at java.base/java.lang.Class.forName(Unknown Source)
[2024-02-13 19:07:35.240] [error] 	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
[2024-02-13 19:07:35.240] [error] 	... 7 more
[2024-02-13 19:07:35.240] [error] Caused by: java.lang.ClassNotFoundException: io.github.nilsen84.lcqt.patches.ClassloaderPatch
[2024-02-13 19:07:35.240] [error] 	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
[2024-02-13 19:07:35.241] [error] 	at com.moonsworth.lunar.genesis.IOHHIIRCOCOHOHRIRHCORIOCI.findClass(Unknown Source)
[2024-02-13 19:07:35.241] [error] 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[2024-02-13 19:07:35.241] [error] 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[2024-02-13 19:07:35.241] [error] 	... 12 more
[2024-02-13 19:07:35.247] [info]  ] [Genesis/GameBootstrap/main/INFO] Starting game!
[2024-02-13 19:07:35.302] [error] Sending event to Sentry: 1593ce0a47474ddfbffa8f390bcf14f4 (java.lang.IllegalStateException: Failed to boot Minecraft)

**Comment by BanyAdm** [comment]
Easy fix!
Open start menu and search for "Task Manager" and open it.
If your Task Manager is not expanded, expand it by pressing the down arrow button on bottom left (🔽)
Go to "Startup" tab on top if on Windows 10 or on the sidebar if on Windows 11.
Find Lunar Client and select it and click Disable button.
Uninstall LCQT (Lunar Client Qt) and reinstall LCQT but don't launch it.
Restart your PC and launch LCQT
LCQT should work now.

**Comment by BanyAdm** [comment]
nvm this fix got patched :(

**Comment by darshadev2011** [comment]
> Easy fix! Open start menu and search for "Task Manager" and open it. If your Task Manager is not expanded, expand it by pressing the down arrow button on bottom left (🔽) Go to "Startup" tab on top if on Windows 10 or on the sidebar if on Windows 11. Find Lunar Client and select it and click Disable button. Uninstall LCQT (Lunar Client Qt) and reinstall LCQT but don't launch it. Restart your PC and launch LCQT LCQT should work now.

Nuh-uh I daren't uninstall LCQT in case I'm not able to install it again as it's officially screwed

**Comment by Aiyhaaam** [comment]
@koxx12-dev  we're waiting for u bro !

**Comment by darshadev2011** [comment]
@koxx12-dev Yo dude how's it going? It's been about two weeks man

**Comment by darshadev2011** [comment]
@koxx12-dev Dude don't leave us in the dark like this man atleast give us some updates on what's happening.

**Comment by emirsassan** [comment]
> @koxx12-dev Dude don't leave us in the dark like this man atleast give us some updates on what's happening.

i kidnapped koxx he will not gonna update agent

**Comment by oTrqsh** [comment]
Anti anti agent isn't patched, but weave loader is. Download lunar client inject, weave loader's latest version and this anti anti agent and then the agent you want, if it doesn't work it's the agent that you downloaded that is patched.
